# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-24 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20180907_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='show_footer',
            field=models.BooleanField(default=True),
        ),
    ]
