# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overlay', '0001_initial'),
        ('website', '0006_homepage_show_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='violator',
            field=models.ForeignKey(blank=True, help_text='(Optional) Show a violator on this page. To create a violator, go to Snippets > Violators', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='overlay.Violator'),
        ),
    ]
