# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-30 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20181029_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='violator',
        ),
    ]
