# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 14:01
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_remove_homepage_violator'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='announcements',
            field=wagtail.core.fields.StreamField((('violator_announcement', wagtail.snippets.blocks.SnippetChooserBlock('overlay.ViolatorAnnouncement')),), blank=True, help_text='(Optional) Select up to 2 announcements to display in a violator. To create an announcement, go to Snippets > Violator Announcements', null=True, verbose_name='Announcement Violator'),
        ),
    ]
